version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    # open-pull-requests-limit: 3
    schedule:
      interval: ${{secrets.interval}}

  - package-ecosystem: "docker"
    directory: "/"
    # open-pull-requests-limit: 3
    schedule:
      interval: ${{secrets.interval}}
 
