version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    # open-pull-requests-limit: 3
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "10:20"

  - package-ecosystem: "docker"
    directory: "/"
    # open-pull-requests-limit: 3
    schedule:
      interval: "daily"
      time: "10:20"
