name: 'Combine PRs'

# Setting up the configuration input
on:
  workflow_dispatch:
    inputs:
      branch_prefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      ci_required:
        description: 'Only combine PRs that are green (status is success). Set to false if repo does not run checks'
        type: boolean
        required: true
        default: true
      combine_branch_name:
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combine-prs-branch'
      ignore_label:
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'

permissions:
  contents: write # to create a new branch and merge other branches together
  pull-requests: write # to create a new PR with the combined changes
  checks: read # to check if CI is passing or not before combining PRs

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Create Combined PR
      id: create-combined-pr
      uses: github/combine-prs@v3.1.1
      with:
        github_token: ${{ secrets.BOT_PAT }}
