name: 'Combine PRs'

on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      ciMustBeGreen:
        description: 'Only combine PRs that are green (status is success). Set to false if repo does not run checks'
        type: boolean
        required: true
        default: true
      combineBranchName:
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combine-prs-branch'
      ignoreLabel:
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Create Combined PR
      id: create-combined-pr
      uses: github/combine-prs@v3.1.1
      with:
        github_token: ${{ secrets.BOT_PAT }}
        ignore_label: ${{ github.event.inputs.ignoreLabel }}
        ci_required: ${{ github.event.inputs.ciMustBeGreen }}
        branch_prefix: ${{ github.event.inputs.branchPrefix }}

